### ISSUE TITLE
Lines customization

### ISSUE THREAD

**Issue by vonklauz** [BasicPrimitives/react#31]
Hello. I want to change the styles of connection lines between nodes in family chart from that
![image](https://user-images.githubusercontent.com/33288376/106390589-1fb71c80-63fa-11eb-9ec2-895910c7b9b4.png)

to that
![image](https://user-images.githubusercontent.com/33288376/106390612-3f4e4500-63fa-11eb-9824-9493dc292d5f.png)

Please tell me if it is possible to implement this. I'm a little confused about your documentation :)

Thank you!

**Comment by BasicPrimitives** [comment]
We don't support this form of organigram. It is a standard way to display organigram in Power Point or any other diagram editor. It does not work when you have multiple marriages between your family members.
