### ISSUE TITLE
Dragging the chart with the mouse cursor

### ISSUE THREAD

**Issue by vonklauz** [BasicPrimitives/react#32]
Hello, in this example https://basicprimitives.github.io/javascript/ chart may be dragged by clicking the mouse button. As i understood while reading docs, it provides by option "enable panning". But it doesn't work in react version of the library (i mean the whole chart, not individual nodes). Could you tell me please, if react version support chart dragging by the mouse. And if so, how can it be enabled? Thank you :)

**Comment by BasicPrimitives** [comment]
We have not implemented Drag & Scroll in the ReactJS component.
We added extensive support for Drag & Drop in ReactJS based matrixed organizational chart editor demo: https://www.basicprimitives.com/orgeditor
The editor supports all sorts of Drag & Drop operations:
* Drag & Drop within a single diagram component layout
* Drag & Drop from the diagram into another diagram
* Drag & Drop from 3d party component into the diagram component. In that demo, you can search nodes and then drag them back into the diagram.
Additionally, we plan to add support of drag and drop between levels of the matrixed structure. We have a lot of drag operations already. So adding Drag & Scroll probably, is too much.
If we make it work, then it should be enabled by default.  But it conflicts with a regular Drag & Drop implementation, and everybody asks how to disable it.
