### ISSUE TITLE
changing the design of nodes

### ISSUE THREAD

**Issue by shahryar-rp** [BasicPrimitives/react#33]
Hi, hope you are doing well

I wonder how could I change the design from its default to something like in the picture?
I tried editing some elements on the template folder in source code, but the problem is when I deploy the chart on heroku, it rebuild it with default settings.

![Capture](https://user-images.githubusercontent.com/58355247/106710603-40a08d00-6607-11eb-9352-8d3f62a32bb9.JPG)

if there is better way to fully edit the design ( colors, fonts, etc.. ) I would really thankful to show it how.
for example: how can I change the title blue background?
I read the API refrence for OrgChartConfig and found a "itemtitleColor" , but when I pass it to config file with for example "ff0000" color, it doesn't get applied

**Comment by BasicPrimitives** [comment]
Hi, thanks.

You need to take a look at the following sample: https://github.com/BasicPrimitives/react/blob/master/src/Samples/ItemTemplate.js

We recommend this way of item templates customization. Just don't forget to replace 
```JavaScript
import { OrgDiagram } from '../Diagrams';
```

with 
```JavaScript
import { OrgDiagram } from 'basicprimitivesreact';
```
You modified the built-in template used when a developer does not provide any templates at all.

**Comment by BasicPrimitives** [comment]
Look at our `react-demo` repository. It is an end-to-end ReactJS application having the Redux store for state management. You may find it more helpful for ad-hock application development.

**Comment by shahryar-rp** [comment]
Thank you

**Comment by shahryar-rp** [comment]
Hi again,
I added the "template" config option to the config object. everything works fine, but the buttons doesn't get rendered.
I checked the demo on[ this link ](https://www.basicprimitives.com/reactusecases/itemtemplates) and here the buttons doesn't get rendered when we click on a user.

**Comment by BasicPrimitives** [comment]
See ReactJS buttons sample
https://www.basicprimitives.com/reactusecases/buttons
