### ISSUE TITLE
Mouse pointer always in loading state

### ISSUE THREAD

**Issue by adakdhrubajyoti** [BasicPrimitives/react#53]
Hi,

Whenever I am putting the <OrgChart /> component  inside placeholder  the mouse pointer is always loading. And also dots are not appearing according to react-demo project.

![image](https://user-images.githubusercontent.com/90239704/146548084-d13795bf-829e-460a-8646-2073eb2bfd4e.png)

**Comment by BasicPrimitives** [comment]
We are a UI front-end component, we don't load anything. The solution to this problem is to build a small React application and start adding back functionality. There is no possibility to guess what is wrong with application,
