### ISSUE TITLE
How to use custom component which is expandable?

### ISSUE THREAD

**Issue by amit08255** [BasicPrimitives/react#55]
I am stuck how to use custom component here whose size can change when selected on click. It will show expanded data.

**Comment by BasicPrimitives** [comment]
See the intro sample:
https://www.basicprimitives.com/reactusecases/firstorganizationalchart

And look at the diagram sizing sample, probbaly?
[Our web sitehttps://www.basicprimitives.com](https://www.basicprimitives.com/reactusecases/diagramsizing)

If you need more elaborate samples, then check out our react-demo repository, it is the actual source code of our https://www.basicprimitives.com demo site
