### ISSUE TITLE
onCursorChanged and onCursorChanging event handlers not working in React

### ISSUE THREAD

**Issue by amit08255** [BasicPrimitives/react#61]
I am using onCursorChanged and onCursorChanging event handlers in React. But its not working correctly.

Here is link to project: https://replit.com/@cutemick3/AdoredScrawnyZip

**Comment by BasicPrimitives** [comment]
Se our use cases and samples:
OnCursorChanging sample:
https://www.basicprimitives.com/highlightannotations
https://github.com/BasicPrimitives/react-demo/blob/master/client/src/containers/HighlightAnnotations/HighlightAnnotations.js

onCursorChanged
https://www.basicprimitives.com/reactusecases/selectingcursoritem

**Comment by BasicPrimitives** [comment]
Please, send your sample project to our support e-mail

**Comment by amit08255** [comment]
Hi
I found the docs was not correct. Updated and created pull request.
https://github.com/BasicPrimitives/react/pull/62
