### ISSUE TITLE
onItemRender not working with orgDiagramPdfkit

### ISSUE THREAD

**Issue by raval08255** [BasicPrimitives/react#68]
I'm trying to use PDFkit with orgchart. It is working but custom template is not rendering even when onItemRender is passed with templates. Card size is changing from template but custom layout not working with orgDiagramPdfkit

**Comment by BasicPrimitives** [comment]
Organizational Diagram plugin for PDFKit published in BasicPrimitives/javascript repository and does not require React to render. Basic Primitives PDFKit plugin uses PDFKit document API to generate PDF templates, it is designed to support PDF-specific content. 
See the following sample for details: https://github.com/BasicPrimitives/javascript/blob/master/samples/pdfkit.plugins/UserItemTemplate.html
