### ISSUE TITLE
Cannot set properties of undefined (setting 'id') in OrgItemConfig()

### ISSUE THREAD

**Issue by iFlameDev** [BasicPrimitives/react#70]
Hi all, I found a confusing issue inside OrgItemConfig

![image](https://user-images.githubusercontent.com/81409161/209521274-15e3c2a6-584f-482c-a871-44062d9bd17e.png)
this is where I create the OrgItemConfig object

![image](https://user-images.githubusercontent.com/81409161/209521625-50fd2dce-d2e1-4576-981a-5b8f82edfbf3.png)
and this is the result in the console log

![image](https://user-images.githubusercontent.com/81409161/209521789-eafb0f53-7dfd-4a51-a291-3ee989de1a46.png)
on the 6.5.1 version inside React project

I don't have any idea about this error, please help me.

**Comment by BasicPrimitives** [comment]
You have to use `new OrgItemConfig(arguments ....)` construct or provide a regular JSON objects instead.

```
control.setOptions({"items", [
    new primitives.OrgItemConfig({
        id: 0,
        parent: null,
        title: "James Smith",
        description: "VP, Public Sector",
        image: "../images/photos/a.png"
    }),
    new primitives.OrgItemConfig({
        id: 1,
        parent: 0,
        title: "Ted Lucas",
        description: "VP, Human Resources",
        image: "../images/photos/b.png"
    }),
    new primitives.OrgItemConfig({
        id: 2,
        parent: 0,
        title: "Fritz Stuger",
        description: "Business Solutions, US",
        image: "../images/photos/c.png"
    })
]
});
```
