### ISSUE TITLE
Doc examples not working for `react-dnd` v15 and v16

### ISSUE THREAD

**Issue by amit08255** [BasicPrimitives/react#71]
Please update docs and integration to support `react-dnd` v15 and v16

![image](https://user-images.githubusercontent.com/28493237/210727568-a4061f01-7535-49d1-93bb-abd26681cbfb.png)

**Comment by BasicPrimitives** [comment]
The examples are working, but it looks like we need to upgrade them to the latest version again. The whole purpose of our examples is to show that our React component is compatible with React Context and it is possible to integrate it with any DND library. It should be a big deal to do it yourself, but we will take a look.

**Comment by amit08255** [comment]
That would be really helpful. Kindly add an updated integration example
