### ISSUE TITLE
How to change cursor's border color?

### ISSUE THREAD

**Issue by Enflow-io** [BasicPrimitives/react#8]
![2019-10-16_18-12-13](https://user-images.githubusercontent.com/37901074/66999047-faf04600-f0dd-11e9-9b26-c5e2ce10d4a2.png)
On 67 line in node_modules/basicprimitivesreact/dist/Templates/CursorTemplate.js

How could I overwrite this option? Thx

**Comment by BasicPrimitives** [comment]
The code you are looking at is not being used in React component. React component has its own JSX based rendering mechanism.
If you need to change React sources and default templates, see basicprimitivesreact package and the following code
https://github.com/BasicPrimitives/react/blob/master/src/Diagrams/Templates/CursorTemplate.js

For your reference:
JavaScript cursor template samples:
https://www.basicprimitives.com/usecases/cursortemplate

ReactJS
https://www.basicprimitives.com/reactusecases/cursortemplate



2. If you use React ve
